In [1]:
import pandas as pd

C:\Users\pavan\AppData\Local\Temp\ipykernel_5224\4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
data=pd.DataFrame({"text":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"],"output":[1,0,0,1]})

In [3]:
data

text  output
0   people watch ineuron       1
1  ineuron watch ineuron       0
2   people write comment       0
3  ineuron write comment       1

In [8]:
from sklearn.feature_extraction import CountVectorizer

ImportError: cannot import name 'CountVectorizer' from 'sklearn.feature_extraction' (C:\Users\pavan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\feature_extraction\__init__.py)

In [6]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/f6/28/b569523552a11b49dc4d33952f43dedb23792fe8ce2f2151d070d615861a/scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.6.0 from https://files.pythonhosted.org/packages/f3/31/91a2a3c5eb85d2bfa86d7c98f2df5d77dcdefb3d80ca9f9037ad04393acf/scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     -------------------------------------- 60.4/60.4 kB 809.7 kB/s eta 0:00:00
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: C:\Users\pavan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

Bag of Words

In [11]:
Bag_of_Word = CountVectorizer()

In [12]:
document_matrix = Bag_of_Word.fit_transform(data["text"])

In [13]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [18]:
Bag_of_Word.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [14]:
Bag_of_Word.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [17]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]], dtype=int64)

In [19]:
document_matrix[1].toarray()

array([[0, 2, 0, 1, 0]], dtype=int64)

In [20]:
document_matrix[2].toarray()

array([[1, 0, 1, 0, 1]], dtype=int64)

In [21]:
document_matrix[3].toarray()

array([[1, 1, 0, 0, 1]], dtype=int64)

N-Gram

In [23]:
# bigram
bigram = CountVectorizer(ngram_range=(2,2))

In [25]:
bigram_vocab = bigram.fit_transform(data["text"])

In [26]:
bigram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [29]:
bigram.get_feature_names_out()

array(['ineuron watch', 'ineuron write', 'people watch', 'people write',
       'watch ineuron', 'write comment'], dtype=object)

In [32]:
bigram_vocab[0].toarray()

array([[0, 0, 1, 0, 1, 0]], dtype=int64)

In [33]:
bigram_vocab[1].toarray()

array([[1, 0, 0, 0, 1, 0]], dtype=int64)

In [34]:
bigram_vocab[2].toarray()

array([[0, 0, 0, 1, 0, 1]], dtype=int64)

In [35]:
bigram_vocab[3].toarray()

array([[0, 1, 0, 0, 0, 1]], dtype=int64)

In [36]:
# trigram
trigram = CountVectorizer(ngram_range=(3,3))

In [38]:
trigram_voacb = trigram.fit_transform(data["text"])

In [39]:
trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [40]:
trigram.get_feature_names_out()

array(['ineuron watch ineuron', 'ineuron write comment',
       'people watch ineuron', 'people write comment'], dtype=object)

In [42]:
trigram_voacb[0].toarray()

array([[0, 0, 1, 0]], dtype=int64)

In [43]:
trigram_voacb[1].toarray()

array([[1, 0, 0, 0]], dtype=int64)

In [44]:
trigram_voacb[2].toarray()

array([[0, 0, 0, 1]], dtype=int64)

In [45]:
trigram_voacb[3].toarray()

array([[0, 1, 0, 0]], dtype=int64)

mix vocabulary

In [46]:
mix = CountVectorizer(ngram_range=(1,2))        # gives both single and bi gram words

In [47]:
mix_vocab = mix.fit_transform(data["text"])

In [48]:
mix.get_feature_names_out()

array(['comment', 'ineuron', 'ineuron watch', 'ineuron write', 'people',
       'people watch', 'people write', 'watch', 'watch ineuron', 'write',
       'write comment'], dtype=object)

In [49]:
mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

TF-IDF(term frequency - inverse document frequency)

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
tf = TfidfVectorizer()

In [55]:
tfidf = tf.fit_transform(data["text"]).toarray()

In [53]:
tf.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [54]:
tf.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [57]:
tfidf

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [56]:
tfidf[0]

array([0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ])

In [60]:
tfidf[1]

array([0.        , 0.8508161 , 0.        , 0.52546357, 0.        ])

In [61]:
tfidf[2]

array([0.57735027, 0.        , 0.57735027, 0.        , 0.57735027])

In [62]:
tfidf[3]

array([0.61366674, 0.49681612, 0.        , 0.        , 0.61366674])

In [59]:
tf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])